version: '3.7'

services:
  frontend:
    image: frontend-example
    build: ./frontend
    environment: 
      - API_URL=http://localhost:8000
    ports: 
      - 5000:5000
  backend:
    image: backend-example
    build: ./backend
    environment:
      - FRONT_URL=http://localhost:5000
    ports:
      - 8000:8000